"""fix all model relationships

Revision ID: 640fd05d8931
Revises: 
Create Date: 2026-01-28 16:09:11.809717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640fd05d8931'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_reviewed')
        batch_op.drop_column('mpesa_code')
        batch_op.drop_column('notes')
        batch_op.drop_column('location')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_read')
        batch_op.drop_column('subject')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('is_read')
        batch_op.drop_column('notification_type')
        batch_op.drop_column('related_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('receipt_number')
        batch_op.drop_column('status')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_approved')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_available')

    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.alter_column('experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('review_count')
        batch_op.drop_column('completed_sessions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_sessions', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.INTEGER(), nullable=True))
        batch_op.alter_column('experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('receipt_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('mpesa_code', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_reviewed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
